import {
	antinodeCount,
	antinodeCountWithResonanceHarmonics,
} from '../src/day08';

const input = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

test('day 8-1', () => {
	expect(antinodeCount(input)).toBe(14);
});

test('day 8-2', () => {
	expect(antinodeCountWithResonanceHarmonics(input)).toBe(34);
});
